--author Andreas Krennmair
--title Huge Text
--newpage asdf
--huge Test!
--newpage jklö
--huge Text!
--newpage qwertz
--huge Abrakadabra!
--newpage
Normaler Text
---
--huge Simsalabim!
---
--huge Is that a stupid presentation!
---
Normal text.
--newpage
--sethugefont block 
--huge other font
--newpage
--sethugefont standard
--huge This is the end...
